import Head from "next/head";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";
import axios from "axios";

export default function Home() {
  console.log(process.env.NEXT_PUBLIC_CLIENT_ID);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
    </div>
  );
}
